[workspace]
name = "watch-my-cpp"
description = "Watch My Cpp 👀"
version = "0.0.1"
authors = ["Christoph Bunte <christoph.bunte@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[tasks]

[dependencies]
websockets = ">=15.0.1,<16"
python = ">=3.13.5,<3.14"
ruff = ">=0.12.0,<0.13"
pyright = ">=1.1.402,<2"
pydantic-settings = ">=2.10.1,<3"
ccache = ">=4.11.3,<5"
rich = ">=14.0.0,<15"
clang-tools = ">=20.1.7,<21"
treefmt = ">=2.3.1,<3"
prettier = ">=3.6.2,<4"
starlette = ">=0.46.2,<0.47"
uvicorn = ">=0.35.0,<0.36"
watchfiles = ">=1.1.0,<2"
include-what-you-use = ">=0.24,<0.25"
clang-20 = ">=20.1.8,<21"
cppcheck = ">=2.18.0,<3"
